### ISSUE TITLE
'RCTText/RCTSinglelineTextInputView.h' file not found on ios archive

### ISSUE THREAD

**Issue by panda919** [react-native-community/react-native-text-input-mask#128] opened 2019-06-18 09:45 UTC
# Bug

I got "'RCTText/RCTSinglelineTextInputView.h' file not found " error on ios archieve step.
I am using react native version:0.59.8 and     "react-native-text-input-mask": "^1.0.1".

**Comment by sabun123** [comment] 2019-06-18 11:22
Same here, get it every time.

What I've tried:
Clearing XCode's DerivedData folder (only the folder for the project I'm working on). Did not solve the issue.

What generally solves it intermittently:
1. With the project open in XCode, clean the project (CMD+Shift+K).
2. Then remove InputMask.framework from the Embedded Binaries section.
3. Close XCode.
4. Open XCode, let it complete it's indexing.
5. Drag InputMask.framework from Libraries/RNTextInputMask.xcodeproj/InputMask.xcodeproj/Products/InputMask.framework back into Embedded Binaries (under General).

You should then be able to archive. Sometimes I find I have to do this multiple times to make it work.


This seems to be a problem for several libraries that use Swift, and are experiencing the upgrade from previous XCode versions to XCode 10.1 or 10.2. We definitely need a fix.

On React Native version 0.59.9, react-native-text-input-mask 1.0.1, and XCode 10.2.1 on MacOS Mojave 10.14.5.

**Comment by sabun123** [comment] 2019-06-19 17:33
Ok, I went on a wild goose chase but somehow it seems to work as expected now.

Steps I took:
1. With Xcode open and the project indexed, clean it (CMD+Shift+K).
2. Close Xcode (CMD+Q)
3. Open a Terminal
4. Following the steps from here (https://stackoverflow.com/questions/32730312/reason-no-suitable-image-found) :
```
rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang/ModuleCache"
rm -rf ~/Library/Developer/Xcode/DerivedData
rm -rf ~/Library/Caches/com.apple.dt.Xcode
```
5. Open the project in XCode, it should take a lot longer to index (let it complete).
6. Double check to make sure XCode is set to use new build system
File -> Project Settings -> Build system: New Build System (Default)
7. Select project, click on the top Target, click on Build Settings and search for 'embed'. Make sure under Build Options that Always Embed Swift Standard Libraries is set to *Yes*.

After this I was able to *archive* the project and *run* the project without issues (no crashes due to dylib, no archive stops due to 'file not found' errors).

What the above steps do is basically, remove any lingering configurations from older XCode setups, cleans the project build files, and ensures that the Swift library for react-native-text-input-mask is compiled properly. Don't forget to have InputMask.framework inside General under Embedded Binaries.

Hope this helps someone.

**Comment by seunlanlege** [comment] 2019-07-15 10:08
my solution is to cannibalize this library, and include it in your project.

**Comment by panda919** [comment] 2019-07-15 10:20
> my solution is to cannibalize this library, and include it in your project.

would you explain in details?

**Comment by seunlanlege** [comment] 2019-07-15 10:43
clone this https://github.com/RedMadRobot/input-mask-ios in your ios folder,
add the framework and xcodeproj to your project.

add these files to your project

https://github.com/react-native-community/react-native-text-input-mask/blob/master/ios/InputMask/InputMask/Classes/RNMask.swift
https://github.com/react-native-community/react-native-text-input-mask/blob/master/ios/RNTextInputMask.h
https://github.com/react-native-community/react-native-text-input-mask/blob/master/ios/RNTextInputMask.m

you'll need to resolve linking issues, but it highly depends on your set-up, I'm using swift so I had to import InputMask.h(https://github.com/RedMadRobot/input-mask-ios/blob/master/Source/InputMask/InputMask/Classes/InputMask.h) into my bridging header file.

then you'll need to link RNMask.swift to RNTextInputMask.m, just import the Objective-C Generated Interface Header Name, reference https://stackoverflow.com/questions/32098696/import-swift-class-in-objective-c-mymodule-swift-h-file-not-found?rq=1

this should go without saying but remove RNTextInputMask.xcodeproj from your libraries first.

**Comment by ivanzotov** [comment] 2019-07-22 14:23
duplicate of #117

**Closed by ivanzotov** 2019-07-22 14:23 UTC
